trigger: none

extends:
  template: parameters.yml

pool:
  name: 'Default'

variables:
  tfWorkingDir: 'master-repo/VM-Setup-Paramerised'
  group: TerraformSecrets
  tfStateKey: 'vmss.${{ parameters.env }}.tfstate'

stages:
- stage: Destroy
  jobs:
  - job: TerraformDestroy
    steps:

    - task: AzureCLI@2
      displayName: 'Set Azure Subscription'
      inputs:
        azureSubscription: 'Pay-As-You-Go(72b3064e-886c-4c1a-96ca-f29aec41150b)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account set --subscription ${{ parameters.subscriptionId }}

    - task: TerraformTask@5
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(tfWorkingDir)'
        backendServiceArm: 'Pay-As-You-Go(72b3064e-886c-4c1a-96ca-f29aec41150b)'
        backendAzureRmResourceGroupName: 'ado_tfstate_rg'
        backendAzureRmStorageAccount