trigger: none

extends:
  template: parameters.yml

pool:
  name: 'Default'

variables:
  tfWorkingDir: 'master-repo/VM-Setup-Paramerised'
  group: TerraformSecrets
  tfStateKey: 'vmss.${{ parameters.env }}.tfstate'


stages:
- stage: Provision
  jobs:
  - job: Terraform
    steps:

    - task: AzureCLI@2
      displayName: 'Set Azure Subscription'
      inputs:
        azureSubscription: 'Pay-As-You-Go(72b3064e-886c-4c1a-96ca-f29aec41150b)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account set --subscription ${{ parameters.subscriptionId }}

    - task: TerraformTask@5
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(tfWorkingDir)'
        backendServiceArm: 'Pay-As-You-Go(72b3064e-886c-4c1a-96ca-f29aec41150b)'
        backendAzureRmResourceGroupName: 'ado_tfstate_rg'
        backendAzureRmStorageAccountName: 'adotfstatestorageacc'
        backendAzureRmContainerName: 'adotfstatecontainer'
        backendAzureRmKey: '$(tfStateKey)'
    
    - task: TerraformTask@5
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(tfWorkingDir)'

    - task: TerraformTask@5
      displayName: Terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(tfWorkingDir)'
        environmentServiceNameAzureRM: 'Pay-As-You-Go(72b3064e-886c-4c1a-96ca-f29aec41150b)'
        commandOptions: >
          -var="subscriptionId=${{ parameters.subscriptionId }}"
          -var="location=${{ parameters.location }}"
          -var="vmBaseName=${{ parameters.vmBaseName }}"
          -var="vmCount=${{ parameters.vmCount }}"
          -var="vmSize=${{ parameters.vmSize }}"
          -var="business_class=${{ parameter.business_class }}"
          -var-file="$(System.DefaultWorkingDirectory)/$(tfWorkingDir)/main.tfvars"

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(tfWorkingDir)'
        environmentServiceNameAzureRM: 'Pay-As-You-Go(72b3064e-886c-4c1a-96ca-f29aec41150b)'
        commandOptions: >
          -auto-approve
          -var="subscriptionId=${{ parameters.subscriptionId }}"
          -var="location=${{ parameters.location }}"
          -var="vmBaseName=${{ parameters.vmBaseName }}"
          -var="vmCount=${{ parameters.vmCount }}"
          -var="vmSize=${{ parameters.vmSize }}"
          -var="business_class=${{ parameter.business_class }}"
          -var-file="$(System.DefaultWorkingDirectory)/$(tfWorkingDir)/main.tfvars"